### ISSUE TITLE
2.4.0 Support

### ISSUE THREAD

**Issue by bml** [sakserv/hadoop-mini-clusters#12]
Hi @sakserv,

Are there any plans to add support for HDP 2.4.0?

thanks,

Barry

**Comment by sakserv** [comment]
@bml - yes, I would like to add this in the very near future. I have some additional fixes I plan to roll out with that update. Although, the only real changes in 2.4 where updating to Spark 1.6, so it has minimal impact on this project.

**Comment by bml** [comment]
Great, thanks. I'll keep an eye for updates.

Let me know if there is anything I can do to help.

**Comment by sakserv** [comment]
I'm in the process of publishing the 0.1.5 release now, which includes support for HDP 2.4.0 (now the default profile). CI is currently running so it will be a bit yet, but I'll update this issue when it is ready in maven central.

**Comment by sakserv** [comment]
Sorry for the delay, 0.1.5 is now released.

**Comment by bml** [comment]
Awesome, thanks @sakserv!
