### ISSUE TITLE
Oozie dependencies are missing from Maven Central

### ISSUE THREAD

**Issue by RomanKovalik** [sakserv/hadoop-mini-clusters#14]
The minor Oozie versions are no longer on maven central. Is there a reason that you choose to use minor versions for most of the dependencies?

**Comment by sakserv** [comment]
The versions directly align with HDP (Hortonworks Data Platform) release versions and the dependencies live in the Hortonworks nexus repository.

I just did a few builds using varying profiles without issue. Can you share more details on what dependencies were failing?

**Comment by RomanKovalik** [comment]
Ok cool, using SBT with the following ` libraryDependencies += "com.github.sakserv" % "hadoop-mini-clusters-oozie" % "0.1.7"` found at http://mvnrepository.com/artifact/com.github.sakserv/hadoop-mini-clusters-oozie/0.1.7 results in SBT unable to resolve the dependencies since they are now missing from the mvn central repository.

Adding Hortonworks nexus to SBT's resolvers fixed the issue:  `resolvers ++= Seq(
  "nexus" at "http://repo.hortonworks.com/content/repositories/releases/",
)`

**Comment by sakserv** [comment]
Thanks for the follow up, @RomanKovalik - glad to hear you got it resolved.
