### ISSUE TITLE
HBase dependencies out of synch

### ISSUE THREAD

**Issue by bml** [sakserv/hadoop-mini-clusters#3]
I'm trying to use a `HBaseLocalCluster`, but I've noticed that the HBase dependencies in your POM are out of synch with the rest of the dependencies. 

```
<hbase.version>0.98.4.2.2.6.9-1-hadoop2</hbase.version>
```

The HBase dependencies are at version `0.98.4.2.2.6.9-1-hadoop2`, which corresponds to HDP version 2.2.6, while the rest of the dependencies correspond to HDP version 2.3.0. 

Also, since this is a fat JAR, I can't just override these dependencies in my own POM. Are there any plans to release a skinny JAR? This would also allow me to completely exclude dependencies I'm not using right now (Mongo, MySQL, ActiveMQ etc), without having to consume a 100MB+ fat JAR.

**Comment by sakserv** [comment]
@bml - Thanks for reaching out.

There is a version conflict issue with hbase-testing-util and storm-core (the disruptor library) that forced me to downgrade the hbase version. I want to revisit this soon. I also want to create version profiles to allow for supporting more than just the latest and greatest HDP.

I completely agree on the value of ditching the fat jar. As more projects are added, this has gotten worse. Can you elaborate on what you would like to see here? Separate modules for each mini cluster?  I have some thoughts here but would love your input.

**Comment by bml** [comment]
@sakserv Thanks for the quick reply. 

I wasn't using Storm so I didn't notice that conflict, but I can see why you had to downgrade the HBase version. 

Initially I was just thinking that removing the shade plugin would suffice for solving the fat JAR issue (this is what I did locally to exclude dependencies I didn't need), but it seems that separate modules for each cluster may be needed too to solve the dependency conflict.

**Comment by sakserv** [comment]
Thanks, @bml - I'll work on a first draft this week and will check with you to see if meets your needs.

**Comment by bml** [comment]
Thanks!

**Comment by sakserv** [comment]
@bml - I have an early preview of the modules based project. It's not 100% complete, but the individual modules should be ready for testing. I've tried to limit the deps to only what is needed for each module. The HBase deps have also been moved to 2.3.0.0. 

If you have some time to try this out and provide feedback, I'd greatly appreciate it!

Here is a link to the [multimodule branch](https://github.com/sakserv/hadoop-mini-clusters/tree/multimodule)

**Comment by bml** [comment]
@sakserv This is perfect - thanks for all the work! 

I haven't tried all of them, but ones I tried look great (HBase, Kafka, ZK). The modules are much more palatable now (~10KB each instead of one 100MB+ JAR).

**Comment by sakserv** [comment]
@bml - Excellent! Glad to hear that worked better.

I've found some additional places where I can trim dependencies and will be merging those changes soon. 

That merge will also contain HDP version profile support for HDP 2.3.0.0 and 2.3.2.0 (new default), with a plan to continue adding versions going forward. All of these changes will officially be part of the 0.1.0 release I hope to get out this weekend. 

If there is a particular version of HDP you are targeting, I can add it.

Thanks for your assistance with feedback and testing.
