### ISSUE TITLE
Hbase mini clustrer is not supporting multiple client connections

### ISSUE THREAD

**Issue by ashitabh** [sakserv/hadoop-mini-clusters#37]
I tried running 2 client connection to the already running Hbase mini cluster, however, only the first one works the second one creates an error on hbase server and server stops responding.

Does hbase minicluster allows more than one connection ?
I tried setting   .setMaxClientCnxns(10) in zookeeper , but that also didn't help

error message:
up and running...
2017-06-23 07:38:05,809 	FATAL 	RS_CLOSE_REGION-BLRAKU28166400:51269-0 	org.apache.hadoop.hbase.regionserver.HRegionServer 	ABORTING region server blraku28166400.sapient.com,51269,1498199848570: Caught throwable while processing event M_RS_CLOSE_REGION
java.lang.NoSuchMethodError: com.google.common.io.Closeables.closeQuietly(Ljava/io/Closeable;)V
	at org.apache.hadoop.hbase.regionserver.HRegion.doClose(HRegion.java:1526)
	at org.apache.hadoop.hbase.regionserver.HRegion.close(HRegion.java:1367)
	at org.apache.hadoop.hbase.regionserver.handler.CloseRegionHandler.process(CloseRegionHandler.java:138)
	at org.apache.hadoop.hbase.executor.EventHandler.run(EventHandler.java:129)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by sakserv** [comment]
Do you have an example of the code that I can look at? The above looks like there might be multiple versions of commons-io on the classpath, but I haven't been able to recreate it.

**Comment by ashitabh** [comment]
Basically I am starting Hbaseminicluster in file1 and testing the connecitons from file2 and file 3 . 
Code in file 1:
*********************************************************************************************
  val zookeeperLocalCluster = new ZookeeperLocalCluster.Builder()
      .setPort(zookeeperPort)
      .setTempDir("./target/embedded_zookeeper")
      .setZookeeperConnectionString(zookeeperConnectionString)
      .setMaxClientCnxns(60)
      .setElectionPort(20001)
      .setQuorumPort(20002)
      .setServerId(1)
      .setTickTime(2000)
      .build()
    zookeeperLocalCluster.start()

    val hbaseLocalCluster = new HbaseLocalCluster.Builder()
      .setHbaseMasterPort(25111)
      .setHbaseMasterInfoPort(-1)
      .setNumRegionServers(2)
      .setHbaseRootDir("./target/embedded_hbase")
      .setZookeeperPort(zookeeperPort)
      .setZookeeperConnectionString(zookeeperConnectionString)
      .setZookeeperZnodeParent("/hbase-unsecure")
      .setHbaseWalReplicationEnabled(false)
      .setHbaseConfiguration(new Configuration())
      .build()
    hbaseLocalCluster.start()
    println("up and running...")
    Thread.sleep(5000000)
    println("shutting down")
    Try(hbaseLocalCluster.stop(true))
    Try(zookeeperLocalCluster.stop(true))

********************************************************************************************
Code in file 2 
	val zookeeperHost = "localhost"
    val zookeeperPort = 12345
    val zookeeperConnectionString = s"${zookeeperHost}:${zookeeperPort}"
	
    val conf = HBaseConfiguration.create()
    conf.set("hbase.zookeeper.property.clientPort", zookeeperPort.toString)
    conf.set("hbase.zookeeper.quorum", zookeeperHost)
    conf.set("zookeeper.znode.parent", "/hbase-unsecure")

    val connection = ConnectionFactory.createConnection(conf)
    val admin = connection.getAdmin()

    val tableName = TableName.valueOf("test")
    val columnFamilyName = "cf1"

    val tableDescriptor = new HTableDescriptor(tableName)
    tableDescriptor.addFamily(new HColumnDescriptor(columnFamilyName).setCompressionType(Algorithm.NONE))


    if(admin.tableExists(tableName)) {
      admin.disableTable(tableName)
      admin.deleteTable(tableName)
    }
    admin.createTable(tableDescriptor)


    val table = new HTable(conf, tableName)
    val key = toBytes("tim")
    val p1 = new Put(key)
    val family = toBytes("cf1")
    val ageColumn = toBytes("age")
    p1.addColumn(family, ageColumn, toBytes(36))
    table.put(p1)

    val get = new Get(key)
    val result = table.get(get)
    val age = Bytes.toInt(result.getValue(family, ageColumn))
    println(s"stored age: $age")


    connection.close()


    val connection2 = ConnectionFactory.createConnection(conf)
    val admin2 = connection2.getAdmin()




    if(admin2.tableExists(tableName)) {
      admin2.disableTable(tableName)
      admin2.deleteTable(tableName)
    }
    admin2.createTable(tableDescriptor)



    table.put(p1)


    val result1 = table.get(get)
    val age1 = Bytes.toInt(result1.getValue(family, ageColumn))
    println(s"stored age: $age1")


    connection.close()
**************************************************************************************

here, I am creating connection 2 times , actually I wanted to use minicluster as a stand alone hbase server for testing multiple hbase jobs performing different functions ( insert , update , delete on the same table) from different jobs

**Comment by sakserv** [comment]
Really sorry for the delay, it's been a busy week. Did you find a solution to this? Is so, would you mind sharing what you found? Thanks!

**Comment by ashitabh** [comment]
Couldn't find the real reason. I just removed all unwanted modules from Intellij and restarted IntellijIDE. Now I am not facing any issue , I can open multiple connections to Hbase. Thanks

**Comment by sakserv** [comment]
Thanks for the response @ashitabh
