### ISSUE TITLE
release 0.1.14 not on maven central

### ISSUE THREAD

**Issue by jetoile** [sakserv/hadoop-mini-clusters#46]
Hello,

It seems that hadoop mini clusters 0.1.14 has not been released on maven central.

Any ideas?

Thanks.

Khanh

**Comment by sakserv** [comment]
Hey @jetoile - sorry about that, it seems there was an issue when I released the artifact via sonatype's nexus. I tried again and it looks to have completed. Let me know if it doesn't show up in the next couple hours. Thanks!

**Comment by sakserv** [comment]
The artifacts are now in maven central. Feel free to reopen this if there are still issues. Thanks!
