### ISSUE TITLE
Can't load library - windows_libs\2.6.2.0\lib\hadoop.dll

### ISSUE THREAD

**Issue by vishwajeetdusane** [sakserv/hadoop-mini-clusters#47]
Looks like windows_libs\2.6.2.0 is not updated yet in master. Project is failing with 2.6.2.0 profile.

**Comment by sakserv** [comment]
Sorry for the oversight. I had not been keeping the windows libs up to date. I have corrected this. Please feel free to reopen if you still encounter issues using trunk.

**Comment by vishwajeetdusane** [comment]
Great, Thanks @sakserv
