### ISSUE TITLE
Support for Kafka 0.10.x and 0.11.y

### ISSUE THREAD

**Issue by timvw** [sakserv/hadoop-mini-clusters#48]
It seems that the Time interface has been moved from kafka.utils.Time to org.apache.kafka.common.utils.Time;

How can we integrate this cleanly? (The changes to the pom are just there for me to run the tests) 
https://github.com/timvw/hadoop-mini-clusters/commit/36295c94d3b7b5b7297a79a7f6199666296f2c41

**Comment by sakserv** [comment]
Hey @timvw - thanks for taking the time to open this. Currently, HDP ships 0.10 AFAIK, and I've tried to align releases to HDP version. Please correct me if I'm wrong. 

To make sure I understand, the ask is to also support 0.11, correct? I believe scala 2.10 is no longer an option for 0.11, so we'll need to move to kafka_2.11. Did you have a specific kafka version in mind? I don't see any 0.11 in the HDP repos.

**Comment by sakserv** [comment]
I'm looking to restructure the project for Hadoop/HDP 3, given the wide range of changes. This should make it easier to support different versions of a particular service. Given this, and the lack of discussion on this topic, I'm going to close this issue. Please reopen if this is still needed.
