### ISSUE TITLE
Support for System property of HADOOP_HOME in windows

### ISSUE THREAD

**Issue by NoRights** [sakserv/hadoop-mini-clusters#49]
I tried to run mini yarn cluster but while starting i got followed exception:
```
java.lang.UnsatisfiedLinkError: 
Can't load library: C:\develop\myfolder\..\.\windows_libs\null\lib\hadoop.dll
```
although that i have my HADOOP_HOME setup correctly.

**Comment by sakserv** [comment]
The "null" part of the path would indicate that you don't have a profile version set. What is HADOOP_HOME set to?

**Comment by NoRights** [comment]
Created pull request for this issue

**Comment by sakserv** [comment]
Thanks @NoRights - the fix makes sense. I'll keep an eye on the CI runs and will merge it when those wrap up.

**Comment by sakserv** [comment]
Thanks for the PR @NoRights ! It has been merged.
