### ISSUE TITLE
NPE when using KdcLocalCluster

### ISSUE THREAD

**Issue by ekohlwey** [sakserv/hadoop-mini-clusters#51]
On version 0.1.14 an NPE happens when using `KdcLocalCluster` in `KeyStoreTestUtil` on line 51. This code inspects the URL provided from the classloader in order to find the classpath of the local cluster.

The code as written will work for the build before sources are archived but will not work when the classes are in JAR files. The reason for this is that `url.toURI().getPath()` will return `null`. Its not clear why this is the case but string manipulation based on the first occurrence of `/` would probably work better.

Additionally, the substring manipulation used in this class won't remove the `!`, and it will only refer to the one JAR file instead of everything in that folder. Its not clear whether or not this is actually desirable - I would need to drill further into where this classpath is used later.

**Comment by Shastick** [comment]
/bump: running into the same issue, and reached the same conclusion as ekohlwey :)

**Comment by sakserv** [comment]
Truly sorry for the delay. Free time has been difficult to come by lately.

I have just pushed a fix to this issue and will make it part of the next release, which I hope to have out by the end of the weekend.
