### ISSUE TITLE
Class not found Exception while running HBASE Mini Cluster (org.apache.hadoop.hbase.backup.impl.BackupException)

### ISSUE THREAD

**Issue by the-ram** [sakserv/hadoop-mini-clusters#52]
I have an existing project running storm that writes into HBASE. As a result i use HBASE client libs. When i run this i get a class not found exception.
I am pretty sure it is a class conflict with the HBASE client libraries , as i can get this to run clean on a project that has no HBASE client dependencies. 
I use an older version of HBASE libs 
			<groupId>org.apache.hbase</groupId>
			<artifactId>hbase-client</artifactId>
			<version>1.1.2</version>
and i tried multiple versions of the mini cluster to see if it works (0.1.6 to 0.1.14). Would anyone know which versions work well together ? or rather for 1.1.2 is there a compatible version
[Error.log](https://github.com/sakserv/hadoop-mini-clusters/files/1514533/Error.log)

**Comment by sakserv** [comment]
Sorry for the delay here. The hbase version leveraged in the mini cluster project is 1.1.2. Can you post your pom.xml so I can try to find a fix?

**Comment by the-ram** [comment]
Hello Shane , attached is the POM. I have tried combinations including the hbase-master and backup jars in the pom in various scopes. I think the issue is with the hbase-client jars and phoenix-jars that i already use
[pom.zip](https://github.com/sakserv/hadoop-mini-clusters/files/1716124/pom.zip)

**Comment by batramanuj** [comment]
How did you fix this?

**Comment by cxiiiiiii** [comment]
delete the dependency of hbase-client in your pom 
hope this will help you
