### ISSUE TITLE
support request - dfs mini cluster

### ISSUE THREAD

**Issue by saranheartmail** [sakserv/hadoop-mini-clusters#57]
If we want to connect dfs mini cluster  like hdfs://dfsminiclusteripaddress:port/   instead of local host.  Most of the blogs never taked about remote connection from hadoop client. I 
 Will this package support for remote connectivity from hadoop client. If not could you please explain what would be the difficulties to acheive connect this cluster from remote machine?.

**Comment by sakserv** [comment]
The main challenges are around HDFS protocol version mismatch. Your HDFS client must speak the same version as the HDFS servers. Note that most HDFS client tutorials are actually outlining connecting to a remote server. fs.defaultFS in your configuration is what determines where the connection should go.

Here is an example HDFS client:
https://gist.github.com/ashrithr/f7899fdfd36ee800f151
