### ISSUE TITLE
Bump to HDP 2.6.5

### ISSUE THREAD

**Issue by explicite** [sakserv/hadoop-mini-clusters#64]
Hi @sakserv,

We are planning bum HDP to 2.6.5 and we need to test somehow our code. Can you release for https://docs.hortonworks.com/HDPDocuments/HDP2/HDP-2.6.5/bk_release-notes/content/comp_versions.html

Cheers,
JP

**Comment by sakserv** [comment]
@explicite - I just committed the necessary changes for 2.6.5 to master. Can you take a look to make sure it works for you? If so, I'll officially release it. Thanks again for the contributions!

**Comment by explicite** [comment]
Hi @sakserv, looks good (minor fixes in PR's). Do we have any ETA?

**Comment by sakserv** [comment]
@explicite - thanks again for the contributions. I have released 0.1.16 which includes support for HDP 2.6.5. The artifacts should be available from Maven central any time now. Feel free to open a new issue if you encounter any issues.
